version: '3.5'
services:
  # app:
  #   build: .
  #   container_name: web
  #   environment:
  #     - DATABASE_URL=postgresql://postgres:postgres@db:5432/ksolves?schema=public

  #   ports:
  #     - '3000:3000'
  #     - '5555:5555'
  #   depends_on:
  #     - db

  db:
    image: postgres:16.4-alpine3.20
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ksolves
    ports:
      - 5432:5432
